### ISSUE TITLE
[Q] Hyperband badly documented. `min_iter` doesn't do what is expected

### ISSUE THREAD

**Issue by jbmorgado** [wandb/wandb#1884]
I am trying to run a sweep with `hyperband` but I am facing two issues. First, the documentation on wandb is quite lacking. Nowhere it says what the 4 parameters are supposed to mean (it does direct you to the paper, but it's complex to understand those even from there).

Second, the `min_iter` parameter for `hyperband`, should specify the minimum iteration before stopping? If so it's not working, no matter what I put for `min_iter` (and also for `s`) it stops as early as 2 iterations into the process. I want it to carry out for at least 7. Here is the code:

```
early_terminate:
  type: hyperband
  s: 2
  min_iter: 7
  max_iter: 19
 ```
