### ISSUE TITLE
[Feature] Run grid sweep in random order

### ISSUE THREAD

**Issue by ianbenlolo** [wandb/wandb#2848]
Running a sweeps in grid search is great but when single runs take long, id like it to run in a random order so that i can get a clearer image of the final results earlier on during the runs.   
ie. if my grid search has 
```
method: grid
[...]
parameters:
    model: 
        values:
            - a
            - b
            - c
    lr: 
        values:
            - 0.00001
            - 0.0001
            - 0.005
    drop:
        values:
            - 0.08
            - 0.01
```
I'd like to get a sense of how each model performs early on, rather than having a full look of the first model, then second, ...

I'd like the grid method to have an option of passing the parameters in a more random order.  

Not many alternatives exist other than not running with wandb. 

Please let me know if this is clear.
Thanks!
