### ISSUE TITLE
List as inputs in sweep yaml 

### ISSUE THREAD

**Issue by rogelioamancisidor** [wandb/wandb#2939]
**Python version: 3.6.9**
**wandb version 0.12.5**
**OS: Linux**

**Summary:** In my code `run.py` I use `argparse` for specifying the model's hyperparameters. One of those parameter is the number of hidden layers and their size, which is specified by a list i.e.

`parser.add_argument("--layers_size_prior", default=[500, 500, 500], nargs='+', help="No of units in then hidden layers", type=int)`

Then, I can specify the size of `--layers_size_prior` simply as `python run.py --layers_size_prior 100 100` for example. 

I want to use `sweep` for parameter optimization for `--layers_size_prior`  and I create the following `yaml` file

    project: my_project
    program: ./run.py
    method: grid
    metric:
      name: auc
      goal: maximize
    parameters:
      layers_size_prior:
         values: [500 500 500, 1000 1000 1000]

but I get the following error message

    ValueError: invalid literal for int() with base 10: ' '

Which makes me think that there is no `nargs='+'` functionality in `sweep`. 

As a workaround, I did something similar as in [using tuple in sweeps](https://github.com/wandb/client/issues/1493)

**Comment by dannygoldstein** [comment]
hi @rogelioamancisidor, i think the issue here is that the values `500 500 500` and `1000 1000 1000` do not get parsed as lists in yaml. if you want them passed to your `--layers_size_prior` arg as a list, try specifying them as a list in yaml:

```yaml
project: my_project
program: ./run.py
method: grid
metric:
  name: auc
  goal: maximize
parameters:
  layers_size_prior:
     values: [[500, 500, 500], [1000, 1000, 1000]]
```

**Comment by rogelioamancisidor** [comment]
It passes a string, i.e. `['1000 1000 1000']`, so it crashes.

**Comment by dannygoldstein** [comment]
hi @rogelioamancisidor, as a workaround, you can do:

sweep.yaml:
```yaml
project: my_project
program: ./run.py
method: grid
metric:
  name: auc
  goal: maximize
parameters:
  layers_size_prior:
     values: ["500 500 500", "1000 1000 1000"]
```

run.py:
```python
#!/usr/bin/env python

import argparse
class ParseAction(argparse.Action):
    def __call__(self, parser, namespace, values, option_string=None):
        print('%r %r %r' % (namespace, values, option_string))
        values = list(map(int, values.split()))
        setattr(namespace, self.dest, values)

parser = argparse.ArgumentParser()
parser.add_argument("--layers_size_prior", default=[500, 500, 500], help="No of units in then hidden layers", action=ParseAction)
args = parser.parse_args()

import wandb
wandb.init()
print(wandb.config)
```

i verified locally that this works. can you let me know if this fixes things for you?

**Comment by dannygoldstein** [comment]
reference: https://docs.python.org/3/library/argparse.html#action

**Comment by rogelioamancisidor** [comment]
@dannygoldstein Thanks for the suggestion. I'll check it out soon and let you know.

**Comment by HilaManor** [comment]
Are you planning on creating a fix for nargs input?

**Comment by andreimargeloiu** [comment]
+1

**Comment by Yaxit** [comment]
+1

**Comment by ghafeleb** [comment]
+1

**Comment by sydholl** [comment]
We are closing this issue due to inactivity. If you feel that it merits additional review, please provide a reproduction and add a comment explaining why. Thank you.

**Comment by carschandler** [comment]
When using something like
```
parameters:
  kernel-sizes:
    values:
      - "3 3 2"
      - "2 2 1"
      - "4 3 2"
```

this is how it gets input to the python script:

```
About to run command: /usr/bin/env python grid.py "--kernel-sizes=3 3 2"
```

`argparse` won't recognize this as a list of numbers because they are quoted, so it will see them as the string "3 3 2" rather than the sequence of strings "3" "3" "2". With `parser.add_argument("--kernel-sizes", type=int, nargs="+"` (or `nargs="*"`) it would not be able to parse the former but would be able to parse the latter.
