### ISSUE TITLE
[Q] passing arguments as a list for wandb sweeps

### ISSUE THREAD

**Issue by allanchan339** [wandb/wandb#3666]
I have tried to use sweep for some parameter tuning. I have some args. as a list. For example patch_size==[2,4]
I have modified the args parser for customized action as follow so that I can parse a string like "2 4"
```
from argparse import Action

class ParseStr2List(Action):
    def __call__(self, parser, namespace, values, option_string=None):
        print('%r %r %r' % (namespace, values, option_string))
        values = list(map(int, values.split()))
        setattr(namespace, self.dest, values)

```
However, when sweep agents start to work, sweeps send command as 
```
2022-05-16 17:45:26,265 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python main.py --batch_size=256 --experiment_name=sweep "--local_patch_size=2 2" --model_name=model "--next_dim=60 720" "--patch_size=4 8" --window_size=3 
```

While I expect to receive an command as 
```
/usr/bin/env python main.py --batch_size=256 --experiment_name=TwinsSVT_group_sweep --local_patch_size="2 2" --model_name=TwinsSVT_1d_group --next_dim="60 720" --patch_size="4 8" --window_size=3 
```

Last but not least, here is my yaml.

```
program: main.py
method: grid
metric:
  goal: maximize
  name: Test/tight/average_mAP
parameters:
  experiment_name:
    values:
      - sweep
    distribution: categorical
  window_size:
    max: 5
    min: 3
    distribution: int_uniform
  model_name:
    values:
      - model
    distribution: categorical
  batch_size:
    value: 256
    distribution: constant
  patch_size:
    values: 
      - "8 4"
      - "4 8"
  local_patch_size:
    values: 
      - "2 4"
      - "4 2"
  next_dim: 
    values: 
      - "60 720"
      - "64 512"
      - "90 1080"

```
