### ISSUE TITLE
[CLI]: Hyperparameter Sweeps doesn't Work for Nested Configs if wandb is Run Locally

### ISSUE THREAD

**Issue by rachmadionl** [wandb/wandb#3702]
### Describe the bug

When I tried nested configurations for hyperparmater sweeps locally, it returns `Invalid sweep config: invalid hyperparameter` error.
EDIT: I could run sweep with nested configuration if wandb is run from **cloud**. Apparently this bug appears only when I run wandb **locally**.

``` 
description: sweep using nested params

# Training script to run
program: train-nested-cli.py

# Method can be bayes, random, grid
method: grid

# Metric to optimize
metric:
  name: loss
  goal: minimize

# Parameter space to search
parameters:
  batch_size:
    values: [32, 64]
  optimizer:
    parameters:
      # lr parameter is nested behind "optimizer"
      lr:
        values: [0.001, 0.0001]
      nadam:
        parameters:
        # beta parameter is nested behind "opimizer.nadam"
          beta:
            values: [0.9, 0.95]
```

```shell

Invalid sweep config: invalid hyperparameter configuration: optimizer
```

### Additional Files

The config files above was taken from the example here: https://github.com/wandb/sweeps/blob/master/examples/nested-params/using-cli/sweep-nested.yaml

### Environment

WandB version: 0.12.16

OS: Ubuntu 18.04

Python version: 3.8.13

Versions of relevant libraries:
