### ISSUE TITLE
[Q] Can sweep explore the parameters of the list argument?

### ISSUE THREAD

**Issue by jin0g** [wandb/wandb#3791]
I have a program that receives the arguments of the list with the following argument parser. Is it possible to explore this in a sweep.yaml? The program itself has a variable number of arguments, but when exploring it, it is enough about a fixed number of arguments. I would like to do a Bayesian search for each argument.

Parser part of a Python script:
```python
parser.add_argument('--numbers', nargs=3)  # or nargs='*'
```

Example of execution on command line:
```bash
$ python example.py --numbers 1 2 3
```

Example of a yaml file I would like to write (but this will NOT work):
```yaml
program: example.py
method: bayes
metric:
  name: validation_loss
  goal: minimize
parameters:
  numbers[0]:
    min: 1
    max: 9
  numbers[1]:
    min: 1
    max: 9
  numbers[2]:
    min: 1
    max: 9
```

**Comment by lesliewandb** [comment]
Hi, thank you for giving me your current .yaml file. For each of your parameters, can you specify the distribution for example 

```
program: example.py
method: bayes
metric:
    name: validation_loss
    goal: minimize
parameters:
    numbers[0]:
        distribution: uniform
        min: 1
        max: 9
    numbers[1]:
        distribution: uniform
        min: 1
        max: 9
    numbers[2]:
        distribution: uniform
        min: 1
        max: 9
```
