### ISSUE TITLE
[CLI]:  Sweep nested parameters 

### ISSUE THREAD

**Issue by EhssanD** [wandb/wandb#3827]
### Describe the bug

The grid search does not work properly with nested config. It fails to iterate over possible values and never ends.

```yml
program: test_run.py
method: grid
metric:
  goal: minimize
  name: val_loss
parameters:
  optimizer:
    parameters:
      learning_rate:
        values: [0.01, 0.001]
      momentum:
        value: 0.9
```
```python 

import wandb

defaults = dict(
    optimizer={
        "learning_rate": 0.2,
        "momentum": 0.9
    },
)

wandb.init(config=defaults)
wandb.log({
    "val_loss": 0.7
})
```

### Environment

WandB version: 0.12.18

OS: Ubuntu 18.04

Python version: 3.8.12
