### ISSUE TITLE
[Feature]: Hierarchical column headers for Runs Table

### ISSUE THREAD

**Issue by LarsHill** [wandb/wandb#3960]
### Description

It would be great if wandb automatically recognizes a hierarchical structure in logged configs to improve the visualization of the runs table. 

Currently a config using some hierarchy, e.g.:
```yaml
Processing:
    remove_stop_words: true
    lowercase: true

Training:
    model_params:
        type: "mlp"
        hidden_dims: [256, 128]
    data_loading_params:
        batch_size: 64
        drop_last: false
```
will be flattened, so that an individual column header looks like "Training/model_params/type".
From a visualization point of view this is quite bad because due to limited horizontal space only the beginning of each column header is visable and thus, every column looks the same (see the screenshot below).

![wandb_runs_table_column_header](https://user-images.githubusercontent.com/37187985/180037855-36b91f6c-fb3c-4e34-abb3-cf1cae203320.png)

### Suggested Solution

It would be great if the hierarchy of column headers is represented in the table layout, e.g. 
![wandb_runs_table_mockup](https://user-images.githubusercontent.com/37187985/180040698-e734134c-32e0-4d7b-ad8b-6d353488c34a.png)

Ideally one could reorder columns based on higher level headers as well. If a low level header is moved outside of the higher level header, then the higher level header can be copied, e.g.
![wandb_runs_table_mockup_reorder](https://user-images.githubusercontent.com/37187985/180041552-2e5c3442-5af8-4822-8e11-ff4ea2758fa9.png)

This way each column can be identified very quickly and the hierarchical grouping organizes the hyperparameters in a nice way.

### Alternatives

For backward compatibility this could be an optional feature which a user can toggle on and off. The default would be the "flat" layout and optionally a user can toggle on a button to visualize the runs table with hierarchical headers.
