### ISSUE TITLE
[Q] How to use wandb sweep with a yaml config

### ISSUE THREAD

**Issue by icedpanda** [wandb/wandb#4151]
Hi,

I want to use sweep for hyperparameter tuning. However, all my arguments are read from a `.ymal` file rather than command line arguments, so I only need to run `python main.py`.

I used to use `ArgumentParser` and `parser.add_argument` for all arguments in other projects, and it was easy to use `sweep`. But it was now too much as I had so many arguments, so I decided to use a `.yaml` file.

Would it be possible to use `sweep` in this case?

Example of my `config.yaml`
```yaml
model: GNN
dataset: tmdb
transformer:
  n_layers：2
  n_heads: 8
pre:
  epoch：1
  lr: 0.1
rec:
  epochs: 1
  lr: 0.01
gen:
  epochs:1
  lr:0.01
```

How I load `config.yaml`
```python
config_dict = {}
with open(args.config, 'r', encoding='utf-8') as f:
    config_dict |= yaml.safe_load(f.read())
```

Thank you in advance
