### ISSUE TITLE
[Q]Whether the searched parameters support parameter nesting

### ISSUE THREAD

**Issue by PussInCode** [wandb/wandb#4428]
I recently searched for parameters according to the following conditions, it seems that this format cannot be used

wandb.errors.CommError: Invalid sweep config: invalid hyperparameter configuration: optimizer

```
  sweep_config:
    project: In_Housing
    entity: chem_mtl
    metric:
      name: val_loss
      goal: minimize
    method: bayes
    parameters:
      optimizer:
        name:
          values: [ 'Adam','SGD' ]
        lr:
          values: [ 1e-3,5e-3,1e-4,5e-4,1e-5,5e-5 ]
        weight_decay:
          values: [ 1e-3,5e-3,1e-4,5e-4,1e-5,5e-5 ]
      lr_scheduler:
        name:
          value: StepLR
        step_size:
          values: [ 50,100 ]
        gamma:
          min: 1e-1
          max: 1.0
      bs:
        values: [ 64,128 ]
      G1:
        name:
          value: G1_Decoder
        p:
          values: [ 0.1,0.2,0.3,0.4,0.5 ]
      G2:
        name:
          value: G2_Decoder
        p:
          values: [ 0.1,0.2,0.3,0.4,0.5 ]
      G3:
        name:
          value: G3_Decoder
        p:
          values: [ 0.1,0.2,0.3,0.4,0.5 ]
      G4:
        name:
          value: G4_Decoder
        p1:
          values: [ 0.1,0.2,0.3,0.4,0.5 ]
        p2:
          values: [ 0.1,0.2,0.3,0.4,0.5 ]
```
