### ISSUE TITLE
[Q]wandb can access the value of other variables？

### ISSUE THREAD

**Issue by PussInCode** [wandb/wandb#4504]
dopout is a list, I hope to search the list, is there any good way
```
   G1:
        parameters:
          name:
            value: Mpn_Decoder
          other_arg:
            parameters:
              component_num:
                value: 3
              ffn_num_layers:
                value: 2
              ffn_hidden_size:
                value: [300]
              p1:
                values: [ 0,0.05, 0.1,0.15,0.2,0.25,0.3,0.35,0.4,0.45,0.5 ]
              p2:
                values: [ 0,0.05, 0.1,0.15,0.2,0.25,0.3,0.35,0.4,0.45,0.5 ]
              dropout:
                  value: [p1,p2]
```
