### ISSUE TITLE
[Q] How to do a hyperparameter sweep using Hydra?

### ISSUE THREAD

**Issue by brian8128** [wandb/wandb#4686]
I'm trying to do a test hyperparameter sweep using hydra. My `train.py` is:
```
import numpy as np
import hydra
import omegaconf
from omegaconf import DictConfig
import wandb
wandb.login()

@hydra.main(config_path="configs", config_name="config")
def main(cfg: DictConfig):
    wandb.config = omegaconf.OmegaConf.to_container(
        cfg, resolve=True, throw_on_missing=True
    )
    wandb.init(entity=cfg.wandb.entity, project=cfg.wandb.project)

    print(f"{cfg=}")
    print(f"{wandb.config=}")

    result = np.abs(cfg['a']) + np.abs(cfg['b'])
    wandb.log({
        'metric': result
      })

if __name__ == "__main__":
    main()
```

My hydra config living in `configs/config.yaml` is:
```
wandb:
  entity: me
  project: Hello World! 
  mode: online

a: 0
b: -1
```

And my `sweep.yaml` is:
```
# https://docs.wandb.ai/guides/integrations/other/hydra
program: train.py
method: bayes
metric:
  goal: maximize
  name: metric
parameters:
  a: 
    values: [1, 2]
  b: 
    min: 0
    max: 1
command:
  - python
  - ${program}
```

I get the impression that the sweep logic is supposed to merge the two configs at some point but it seems like no merging is happening. When I run `wandb sweep sweep.yaml` and then the command it produces my program outputs: 
```
cfg={'wandb': {'entity': 'me', 'project': 'Hello World!', 'mode': 'online'}, 'a': 0, 'b': -1}
wandb.config={'a': 2, 'b': 0}
```

Shouldn't this get merged automatically somehow into one config?
