### ISSUE TITLE
[Q] Sweep with different argument groupts

### ISSUE THREAD

**Issue by carrtesy** [wandb/wandb#4706]
Hello,

I am trying to run wandb sweep with command like:
```sh
python main.py {argument group 1} **{model_name}** {argument group 2}
```

for example, 
```sh
python train.py --lr 0.01 --epochs 10 --batch_size 64 **ResNet** num_layers 18 hidden_dim 128
```
using subparser of python [argparse](https://docs.python.org/3/library/argparse.html).

```yaml
program: train.py
method: bayes
metric:
  name: validation_loss
  goal: minimize
parameters:
  lr:
    min: 0.0001
    max: 0.1
(...)
```
As I understand, it is not possible to use sweep features if I pass the arguments that way. 
Are there any way to handle this properly?

Thanks in advance.

**Comment by MBakirWB** [comment]
Hi @carrtesy, thank you for writing in an happy to help. Sweeps do support invoking and passing arguments to the training script via the [command line](https://docs.wandb.ai/guides/sweeps/define-sweep-configuration#command). For example, my Yaml file could be configured as follows:

```
program:
  train.py
method: grid
parameters:
  batch_size:
    value: 8
  lr:
    value: 0.0001
command:
  - ${env}
  - python
  - ${program}
  - "-b"
  - your-training-config
  - ${args}
```

The `${args}` key expands to all the parameters in the sweep configuration file, expanded so they can be parsed by `argparse: --param1 value1 --param2 value2`

See this [example here](https://docs.wandb.ai/guides/sweeps/faq#how-do-i-use-custom-cli-commands-with-sweeps) for reference. Please let me know if this sorts things out for you or if you have any additional questions.
