### ISSUE TITLE
Random Search sweep order [Q]

### ISSUE THREAD

**Issue by TangJiakai** [wandb/wandb#4725]
Could you tell me **What is the search order of the parameters under random sweep**, please?  I find it is not ideal when I specify parameters orderly and I guess it is just unorder to get one parameter and then sweep the range of this param. But actually, I hope it sweeps the params in the order specified by me. e.g.
```
learning_rate:
   values: [0.1,0.01]
decay:
  values: [1e-4,1e-5]
batch_size:
  values: [64,128]
```

The ideal order is learning_rate -> decay -> batch_size. However, wandb dosen't follow this rule.
