### ISSUE TITLE
[Q]: Frontend code

### ISSUE THREAD

**Issue by janosh** [wandb/wandb#4819]
Is the frontend source open? Couldn't find it in https://github.com/orgs/wandb/repositories. I'd like to submit a fix.

**Comment by janosh** [comment]
A tiny thing but it's been irking me: Fix the alignment on the clear filter button:

![Screenshot 2023-01-23 at 11 44 16](https://user-images.githubusercontent.com/30958850/214134687-719b5164-a785-44de-adf4-3452dfa21be9.png)

Can be fixed by adding

```css
.filter-list__item {
    display: flex;
    align-items: center;
}
```
