### ISSUE TITLE
[App]: wandb not showing sweep name specified in the YAML but sweep id instead

### ISSUE THREAD

**Issue by AndyJZhao** [wandb/wandb#5162]
### Current Behavior

Wandb WebUI not showing the correct sweep name but shows sweep instead.
In the web UI, the sweep shows the following:
![image](https://user-images.githubusercontent.com/26394168/225178068-32cda839-a00a-46c5-be9a-0e62a70bdfda.png)
However, for each sweep I've specified a name for it **in the YAML file** (an example below).
```yaml
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}
method: grid
name: Test Wandb
parameters:
  total_iters:
    value: 0
  gnn_use_feature:
    values:
      - yes
      - no
program: src/run.py
```
Yet the name is not working.

P.S. The problem seems to be at the YAML side only, through manually updating the sweep name, the name will be updated in the sweep page.
![image](https://user-images.githubusercontent.com/26394168/225180375-45be2611-c54e-44e1-b384-3ca76b5d0212.png)

### Expected Behavior

Showing sweep names instead of ids.

### Environment

OS: MacOS

Browsers: Chrome

Version: 0.13.11
