### ISSUE TITLE
[Feature]: Allow environment variables in the sweep yaml file

### ISSUE THREAD

**Issue by jlperla** [wandb/wandb#5208]
### Description

There are cases when I want to change a single value in a shell script and then run one or more sweeps.  This comes up in creating replication packages.

I would love to be able to refer to environment variables within the yaml specification.

### Suggested Solution

For example, lets say I had an environment variable `export EXPERIMENT_LAYERS="4"`

Then I would love to be able to write the config files like
```yaml
program: investment_euler.py
method: grid
parameters:
  model.layers:
    value: $(EXPERIMENT_LAYERS)
```
with whatever interpolation you have in mind.  e.g. `${ENV:EXPERIMENT_LAYERS}` etc.

If this feature is already there, my apologies, I just didn't see it in the docs.

**Comment by rsanandres-wandb** [comment]
Hello @kptkin!

You can set environment variables in sweeps via [command configuration key](https://docs.wandb.ai/guides/sweeps/define-sweep-configuration#command-) and here is a [GitHub post regarding using a bash script](https://github.com/wandb/wandb/issues/3255) as a workaround.

**Comment by jlperla** [comment]
Thanks.  For this the thing I want to parameterize is actually a W&B sweep setup.  In particular the max value for one of the parameters.

```yaml
program: myscript.py
method: grid
parameters:
  seed:
    min: 1
    max: ${envvar: NUMSEEDS} # number of seeds to try
  optimizer.lr:
     value: 1e-6
```
etc.  Is that possible or is it only thing that can be passed through directly to the CLI?
