### ISSUE TITLE
[CLI]: wandb sweep args_no_hyphens when argument is string does not work with hydra

### ISSUE THREAD

**Issue by famishedrover** [wandb/wandb#5523]
### Describe the bug

```cmd
wandb sweep sweep.yaml
```
and sweep.yaml is defined as 
```yaml
...
parameters:
  agent.name:
    values: ["one string", "two string"]
```

```shell
 wandb.wandb_agent - INFO - About to run command: /usr/bin/env python main.py "agent.name=one string"
```

The expected command that wandb should run is not supposed to have double-quotes around the parameter name. i.e. it should be, 
```shell
 wandb.wandb_agent - INFO - About to run command: /usr/bin/env python main.py agent.name="one string"
```

### Environment

WandB version:
 0.15.2
OS:
MacOS Ventura 13.3 
CentOS
Python version:
3.9
Versions of relevant libraries:
N/A

**Comment by luisbergua** [comment]
Hey @famishedrover, thank you so much for reporting this! Would it be possible to share a code example of `main.py `? Would something like the following reproduce your code?
```
import hydra
import omegaconf
import wandb

@hydra.main(config_path="configs/", config_name="defaults")
def run_experiment(cfg: omegaconf.DictConfig) -> None:
    wandb.init()
    for i in range(5):
        wandb.log({'loss': 1})
run_experiment()
```

**Comment by famishedrover** [comment]
yes, I use something like `@hydra.main(config_path="configs/", config_name="defaults")`. Apart from that running the script throws an error because hydra is unable to parse `python main.py value1=xyz "value2=abc" value3=123` because of the double quotes.

**Comment by luisbergua** [comment]
Hi @famishedrover, thanks for confirming this! I have reproduced this issue on my end so will report it to our Engineering Team. In the meantime, would it work for you to use `_` or `-` instead of whitespaces?

**Comment by kmikowicz-wandb** [comment]
This seems fixed using the current package versions:
`"hydra-core>=1.3.2",
    "omegaconf>=2.3.0",
    "wandb>=0.25.0",`

I have provided the following sweep.yaml
```
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}

name: sweep1
project: <--- OMITTED --->
description: Test sweep
program: main.py
method: grid
parameters:
  agent.name:
    values: ["one string", "two string"]
  agent.value:
    value: "three"
  agent.hyphen:
    value: "three-four"
  agent.quote:
    value: "\"five six\""
```

I am able to submit the sweep and I ran the repro main.py and got the following wandb agent success
2026-03-05 10:44:52,478 - wandb.wandb_agent - INFO - Running runs: []
2026-03-05 10:44:55,213 - wandb.wandb_agent - INFO - Agent received command: run
2026-03-05 10:44:55,213 - wandb.wandb_agent - INFO - Agent starting run with config:
        agent.hyphen: three-four
        agent.name: one string
        agent.quote: "five six"
        agent.value: three
2026-03-05 10:44:55,215 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python main.py agent.hyphen=three-four "agent.name=one string" "agent.quote="five six"" agent.value=three
[redacted]/sdk/WB-25823/main.py:7: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path="configs/", config_name="defaults")
[redacted]/.venv/lib/python3.13/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from [redacted]
wandb: Currently logged in as: [redacted]
wandb: Tracking run with wandb version 0.25.1.dev1
wandb: Run data is saved locally in [redacted]
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run summer-sweep-1
wandb: ⭐️ View project at https://wandb.ai/[redacted]
wandb: 🧹 View sweep at https://wandb.ai/[redacted]
wandb: 🚀 View run at https://wandb.ai/[redacted]
