### ISSUE TITLE
[App]: One sweep config creating multiple sweeps online

### ISSUE THREAD

**Issue by meghbhalerao** [wandb/wandb#5599]
### Current Behavior

My sweep config yaml file is the following - 
```
program: main.py
method: grid
parameters:
  dataset:
    value: cifar10
  num_classes:
    value: 10
  arch:
    values: ['ResNet18']
  phase:
    value: calibration
  summary_parameters.ipc:
    values: [250, 500, 1000, 1500]
  summary_parameters.use_sparse_representation:
    value: false
  summary_parameters.exponent:
    values: [0.001, 0.01, 0.1, 1, 5, 10]
  summary_parameters.knn:
    values:  [2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48]
  summary_parameters.sim_type:
    value: euclidean
  summary_parameters.sparse_type:
    value: [zcopblock, None]
  summary_parameters.smraiz_constrains:
    value: ['partition_matroid']
  recalculate_params.sparsification_clustering:
    value: true
  batch_size:
    value: 20
  summary_parameters.fn_type:
    value: smraiz
  summary_parameters.feat_type_list:
    values: [['convnetd3_1'], ['resnet18_1'], ['clip_vit_b_32']]
  summary_parameters.feat_responsibilities:
    value: [1]
  eval_mode:
    value: cords
  num_eval:
     value: 1
  use_saved_data:
      value: false
  summarization_strategy:
      value: whole
command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
```

when I run `wandb sweep config.yaml` it outputs the following to the console - 

```
wandb: Creating sweep from: cifar10_cords_all_ipc.yaml
wandb: Created sweep with ID: ly5uyrub
wandb: View sweep at: https://wandb.ai/meghbhalerao/smrai-container-documentation-src/sweeps/ly5uyrub
wandb: Run sweep agent with: wandb agent meghbhalerao/smrai-container-documentation-src/ly5uyrub

```
which is expected and fine.

But when I go to the webpage, I see that 2 sweeps are created on the web UI - 
<img width="1234" alt="Screenshot 2023-05-22 at 2 57 48 PM" src="https://github.com/wandb/wandb/assets/33202960/c95fe006-c3dc-46ee-8901-a36f70d19edb">

and the config files for these 2 sweeps are the same inside the UI, but why are 2 sweeps getting created? Is it some bug inside my config file?

### Expected Behavior

Only 1 sweep needs to be created.

### Steps To Reproduce

1. Create the sweep yaml file that I have provided Above.
2. Make a sweep using `wandb sweep config.yaml`
3. Go to wandb website and go under sweeps to see how the sweep is instantiated.

### Environment

OS:
```
   Static hostname: debian
Transient hostname: megh-176-vcpu-box
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 605f692aca9c243c905eb7f1c84e71c0
           Boot ID: 03abf1ed4cd64db3a63e100adac6bcdf
    Virtualization: kvm
  Operating System: Debian GNU/Linux 11 (bullseye)
            Kernel: Linux 5.10.0-23-cloud-amd64
      Architecture: x86-64
```
Browsers:
`Safari`
Version:
`wandb, version 0.14.0`
