### ISSUE TITLE
[CLI]: wandb sweep raises unnecessary `ValueError`

### ISSUE THREAD

**Issue by ahalev** [wandb/wandb#6249]
### Describe the bug

It should be possible to have a hyperparameter value that accepts `None` as an option in a sweep, e.g.:

```yaml
parameters
      noise:
        values: [null, 0.05, 0.25, 0.5]
        probabilities: [0.4, 0.2, 0.2, 0.2]
```

However, [lazy handling of `None` values](https://github.com/wandb/wandb/blob/0e7311d8851a975a78c47197be2253c41e51028e/wandb/sdk/launch/sweeps/utils.py#L228-L230) prevents this by raising a `ValueError` on the assumption a value wasn't found, e.g:

```bash
ValueError: No "value" found for command["args"]["noise"]
```

This is an easy fix, just wrap a `config["value"]` call in a try... except block and raise the ValueError on KeyErrors.

### Environment

WandB version: 0.15.5

OS: MacOS 12.6

Python version: 3.8.17
