### ISSUE TITLE
[Q] Sagemaker launcher setup when connecting through AWS VPC

### ISSUE THREAD

**Issue by mjmonroe** [wandb/wandb#6490]
I have successfully run a Wandb code job through Sagemaker. However, when I try and run an image job through Sagemaker, I always get a boto validation error on the CreateTrainingJob operation. I am using ECR to store the wandb images. It appears that the CreateTrainingJob wandb is generating assumes a non-ecr repo.

Queue Launch config
```yaml
RoleArn: arn:aws:iam::<account id>:role/<sagemaker role>
ResourceConfig:
  InstanceType: ml.m4.xlarge
  InstanceCount: 1
  VolumeSizeInGB: 2
OutputDataConfig:
  S3OutputPath: https:/<bucket name>.s3.us-west-2.amazonaws.com/
StoppingCondition:
  MaxRuntimeInSeconds: 3600
```

Agent Launch config
```yaml
# W&B entity (i.e. user or team) name
entity: <username>
queues:
  - SagemakerTwo

environment:
    type: aws
    region: us-west-2
    account: <account id>
registry:
    type: ecr
    uri: <account id>.dkr.ecr.us-west-2.amazonaws.com/hello_wandb
#    repository: hello_wandb

builder:
  type: docker
```

Wandb launch error
```python
wandb: launch: Launching run on sagemaker with user-provided entrypoint in image
wandb: ERROR launch: Error running job: Traceback (most recent call last):
wandb: ERROR   File "/Users/markmonroe/Documents/wbetest/.conda/lib/python3.10/site-packages/wandb/sdk/launch/agent/agent.py", line 536, in thread_run_job
wandb: ERROR     self._thread_run_job(
wandb: ERROR   File "/Users/markmonroe/Documents/wbetest/.conda/lib/python3.10/site-packages/wandb/sdk/launch/agent/agent.py", line 618, in _thread_run_job
wandb: ERROR     run = backend.run(project, image_uri)
wandb: ERROR   File "/Users/markmonroe/Documents/wbetest/.conda/lib/python3.10/site-packages/wandb/sdk/launch/runner/sagemaker_runner.py", line 236, in run
wandb: ERROR     run = launch_sagemaker_job(
wandb: ERROR   File "/Users/markmonroe/Documents/wbetest/.conda/lib/python3.10/site-packages/wandb/sdk/launch/runner/sagemaker_runner.py", line 371, in launch_sagemaker_job
wandb: ERROR     resp = sagemaker_client.create_training_job(**sagemaker_args)
wandb: ERROR   File "/Users/markmonroe/Documents/wbetest/.conda/lib/python3.10/site-packages/botocore/client.py", line 535, in _api_call
wandb: ERROR     return self._make_api_call(operation_name, kwargs)
wandb: ERROR   File "/Users/markmonroe/Documents/wbetest/.conda/lib/python3.10/site-packages/botocore/client.py", line 980, in _make_api_call
wandb: ERROR     raise error_class(parsed_response, operation_name)
wandb: ERROR botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the CreateTrainingJob operation: TrainingImageConfig with TrainingRepositoryAccessMode set to VPC must be provided when using a training image from a private Docker registry. Please provideTrainingImageConfig and TrainingRepositoryAccessMode set to VPC when using a training image from a private Docker registry.
```
