### ISSUE TITLE
Deprecation warning while using wandb with pytest

### ISSUE THREAD

**Issue by kunaltyagi** [wandb/wandb#6711]
### Describe the bug

```python
import pytest
import wandb

def test_dummy():
    pass
```

```shell
pytest <file>
========================================= warnings summary =========================================
<REDACTED>/lib/python3.11/site-packages/wandb/sdk/launch/builder/build.py:11: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    import pkg_resources

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=================================== 1 passed, 1 warning in 2.57s ===================================
```

### Environment

WandB version: 0.16.1

OS: Ubuntu

Python version: 3.11.6

Versions of relevant libraries: pytest==7.4.3

**Comment by luisbergua** [comment]
Hi @kunaltyagi, thanks for raising this! I just checked on my end using `wandb==0.16.1' but wasn't able to reproduce the warning, tests are passing
```
pytest test.py
========================================================================================= test session starts =========================================================================================
platform darwin -- Python 3.9.12, pytest-7.1.1, pluggy-1.0.0
rootdir: /Users/luisberguasanchez/Desktop
plugins: anyio-3.5.0, typeguard-4.1.5, hydra-core-1.3.2
collected 1 item                                                                                                                                                                                      

test.py .                                                                                                                                                                                       [100%]

========================================================================================== 1 passed in 1.04s ========================================================================================== 
```
Please let me know if there's something that I'm missing!

**Comment by kunaltyagi** [comment]
I can confirm this doesn't happen with a venv, but with conda

```yaml
name: wandb_test

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip # pinning version not necessary
  - pip:
      - pytest==7.4.3
      - wandb==0.16.1
```

**Comment by fmamberti-wandb** [comment]
Hi @kunaltyagi, thanks for providing all the details about the environment. We have now managed to reproduce the issue and we have escalated it internally to review and we will keep you posted.

**Comment by joshuacwnewton** [comment]
It looks like a similar warning was reported in https://github.com/wandb/wandb/issues/5898 with a fix merged in https://github.com/wandb/wandb/pull/5899.

But, that PR targeted only a single instance of `pkg_resources`, when there are [quite a few remaining](https://github.com/search?q=repo%3Awandb%2Fwandb%20pkg_resources&type=code)! :stuck_out_tongue_closed_eyes:

**Comment by sydholl** [comment]
WandB Internal User commented: 
fmamberti-wandb commented: 
Hi @kunaltyagi, thanks for providing all the details about the environment. We have now managed to reproduce the issue and we have escalated it internally to review and we will keep you posted.

**Comment by sydholl** [comment]
WandB Internal User commented: 
kunaltyagi commented: 
I can confirm this doesn't happen with a venv, but with conda

```yaml
name: wandb_test

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip # pinning version not necessary
  - pip:
      - pytest==7.4.3
      - wandb==0.16.1
```
