### ISSUE TITLE
[Q] How to run a wandb.sweep with a python script as a package?

### ISSUE THREAD

**Issue by brendanartley** [wandb/wandb#6868]
Hi there, I am trying to run a wand.sweep with my code structured as a package. For example, I would manually execute the script with this command `python -m src.train`.

The problem is when I try and run a sweep, the incorrect command is executed, and therefore the sweep fails. Here is an example of what I have tested.

```
program: "-m train"
interpreter: python
method: grid
project: test-project
metric:
  name: val_loss
  goal: minimize
parameters:
  lr:
    values: [1e-3, 1e-4, 1e-5]
```

I have tested different combinations of the program and interpreter parameters, but the `-m` is always omitted from the command issued by the sweep. For example, the error msg always looks something like this.

```
2024-01-20 07:36:53,204 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python "-m src.train" --lr=0.001
/bin/python: Error while finding module specification for ' src.train' (ModuleNotFoundError: No module named ' src')
```

Has anyone ran sweeps with a package structure before? If not any ideas would be appreciated!
