### ISSUE TITLE
[CLI]: : Updates to run config and wandb offline runs

### ISSUE THREAD

**Issue by klieret** [wandb/wandb#6974]
### Describe the bug

**Expectation**: If I change the run config (`run.config.update({...}, allow_val_change=True) mid-run and then run `wandb sync /path/to/wandb_dir` externally, the config should be updated in the cloud

**What actually happens:** Changes to the run config are not synchronized until the run is finished. This issue was first [raised](https://github.com/klieret/wandb-offline-sync-hook/issues/81) by @MoH-assan and I've reproduced it.

**Context:** Academic HPC clusters typically run ML experiments on batch nodes without internet. The only way to use wandb is with offline runs that are periodically synced from a head node with internet access (more information in [a python package that I wrote to simplify this workflow](https://github.com/klieret/wandb-offline-sync-hook)). This way, you still get almost-live updates from your runs.

I used the following script to reproduce the issue:

```python
#!/usr/bin/env python3

from pathlib import Path
import os
import wandb
import time
import random
import subprocess
import coolname

os.environ["WANDB_MODE"] = "offline"

name = coolname.generate_slug(2)
run = wandb.init(
    config={"a": 1},
    project="test",
    allow_val_change=True,
    name=name,
    id=name,
    entity="klieret",
)

wandb_dir = Path(run.dir)
config_file_path = wandb_dir / "config.yaml"
print(wandb_dir)


def sync_offline_run():
    cmd = ["wandb", "sync", str(Path(wandb_dir).parent)]
    print(cmd)
    subprocess.run(cmd)


def print_online_config():
    api = wandb.Api()
    run = api.run(f"klieret/test/{name}")
    print(run.config)


def simulate_training():
    for i in range(100):
        run.log({"metric": random.random()})
        time.sleep(0.01)


print("----------------")

simulate_training()
sync_offline_run()
print_online_config()

print("----------------")

run.config.update({"a": 2}, allow_val_change=True)

simulate_training()
sync_offline_run()
print_online_config()

print("----------------")

run.finish()
sync_offline_run()
print_online_config()
```

### Environment

WandB version: 0.16.3

OS: OSX

Python version: 3.11.3

Versions of relevant libraries:

**Comment by ArtsiomWB** [comment]
Hi @klieret! To confirm, you start an offline run, change its config, then finish the run and sync it to the cloud. Once it's synced it does not have the updated config you are interested in?

**Comment by klieret** [comment]
Hi @ArtsiomWB, thanks for your reply! 

After the run is finished and we manually sync again, the config is updated correctly.

However, any config change while the run is still training will not be synced (even though all `.log` calls are).  

I realize that this is probably a rare use case. However, I wonder if a problem with the pytorch lightning integration could be related: There, I observe that all config items are only synced to the cloud after the run is finished for this same same "offline" synchronization strategy outlined above.

**Comment by ArtsiomWB** [comment]
Thank you for reporting this, @klieret!

I have submitted this concern to our engineering team

**Comment by Karol-G** [comment]
Yes, please! That would be great :)

**Comment by smartinezai** [comment]
I am also having the same issue

**Comment by smartinezai** [comment]
> WandB Internal User commented: klieret commented: Hi [@ArtsiomWB](https://github.com/ArtsiomWB), thanks for your reply!
> 
> After the run is finished and we manually sync again, the config is updated correctly.
> 
> However, any config change while the run is still training will not be synced (even though all `.log` calls are).
> 
> I realize that this is probably a rare use case. However, I wonder if a problem with the pytorch lightning integration could be related: There, I observe that all config items are only synced to the cloud after the run is finished for this same same "offline" synchronization strategy outlined above.

This does not solve the issue.

To clarify, here is the config.yaml that results after the run is finished

```
wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.19.8
    framework: huggingface
    huggingface_version: 4.50.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1743435541
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      - 105
      3:
      - 4
      - 23
      - 42
      - 55
      4: 3.11.6
      5: 0.19.8
      6: 4.50.0
      8:
      - 5
      13: linux-x86_64

```

it does not include any of the config parameters that were updated in the script
