### ISSUE TITLE
[Q] Stuck Iteration and Sync Issue with wandb sweeps for YOLOv7 Hyperparameter Tuning

### ISSUE THREAD

**Issue by Achyar-CN** [wandb/wandb#7093]
I am attempting to utilize wandb sweeps for YOLOv7 hyperparameter tuning using the Bayesian method. Below is the code I used to execute the process:
![image](https://github.com/wandb/wandb/assets/100359668/86d878f8-b07a-4741-b4dd-c8eb2fb1c8ad)

I encountered a condition where the process became stuck in the first iteration, specifically during finalization and synchronization with wandb. However, when I do not use sweeps and only rely on the internal wandb from YOLOv7, it successfully finalizes and syncs to wandb. Unfortunately, this does not address my original goal of using sweeps for hyperparameter tuning.

I have attempted to read the debug-internal.log and debug.log, but I found no clues. What I noticed is that when I run one iteration of sweeps, Wandb keeps syncing and creating some new run folders, never finalizing the process.
![image](https://github.com/wandb/wandb/assets/100359668/1360004d-6b43-459e-a48d-6144fa52ef4c)

Has anyone else encountered the same problem when using sweeps for YOLOv7? If so, could you kindly share any methods to tackle this issue?

**Comment by thanos-wandb** [comment]
Hi @Achyar-CN thank you for writing in. While we don't know how the `train.py` script structure looks like, it seems that way of integrating Sweeps with your code, it can cause issues. You're starting a wandb run, and inside that run's singleton you're calling an external script. Are you starting another run in that script? 

For your use case, it would be most recommended that you define the sweep hyperparameter in a yaml file, and you add in the file the python script and its arguments using a similar format to this one:
https://docs.wandb.ai/guides/sweeps/faq#how-do-i-use-custom-cli-commands-with-sweeps

Please let me know if that would work for you, or if you needed further assistance with this.

**Comment by Achyar-CN** [comment]
Hello @thanos-wandb, thank you for your response. I'm not entirely sure if it was calling an external script and initiating another run. From my understanding, there already exists a wandb, run within the YOLOv7 training process by default. I believe that when I run the sweeps, it also executes the internal wandb scripts.

Based on your suggestion, I have create config.yaml file as follow:
```
program: train_dual.py
method: bayes
metric:
  goal: maximize
  name: metrics/mAP_0.5
parameters:
  epochs:
    values: [2, 3]
command:
  - ${env}
  - python
  - ${program}
  - "--batch"
  - "8"
  - "--epochs"
  - ${args.epochs}
  - "--img"
  - "800"
  - "--device"
  - "0"
  - "--min-items"
  - "0"
  - "--close-mosaic"
  - "15"
  - "--data"
  - "/content/gdrive/MyDrive/YOLOv9_s/yolov9/data/pothole.yaml"
  - "--weights"
  - "/content/gdrive/MyDrive/YOLOv9_s/yolov9/yolov9-c-converted.pt"
  - "--cfg"
  - "/content/gdrive/MyDrive/YOLOv9_s/yolov9/models/detect/yolov9-c.yaml"
  - "--hyp"
  - "/content/gdrive/MyDrive/YOLOv9_s/yolov9/data/hyps/hyp.scratch-high.yaml"
```

However, when I execute the first CLI command, it causes an error.
![image](https://github.com/wandb/wandb/assets/100359668/5b180062-db28-4fe7-bfba-d0209d550752)

I have attempted to adjust the configuration file several times, but I couldn't pinpoint the cause. Could you kindly provide some advice on this matter?

**Comment by Achyar-CN** [comment]
Hello @thanos-wandb, thank you for your response. I'm not entirely sure if it was calling an external script and initiating another run. From my understanding, there already exists a wandb, run within the YOLOv7 training process by default. I believe that when I run the sweeps, it also executes the internal wandb scripts.

Btw, I followed your suggestion regarding the CLI commands, and it worked perfectly. Many thanks for your assistance!

**Comment by elon1992** [comment]
Hello @thanos-wandb, @Achyar-CN Could you please explain me how did you solve this with some more detailed approach. Thanks

**Comment by Achyar-CN** [comment]
Hi @elon1992 ,  here are the steps I've taken for YOLOv7, which I believe also apply to YOLOv9:
0. Ensure that you're in the active directory path for YOLOv7.
1. Create a new 'config.yaml' file, for example:
```
program: train.py
method: bayes
metric:
  goal: maximize
  name: metrics/mAP_0.5
parameters:
  epochs:
    values: [2, 3]
command:
  - ${env}
  - python
  - ${program}
  - ${args}
  - "--batch-size=32"
  - "--img=800"
  - "--device=0"
  - "--workers=4"
  - "--data=/content/gdrive/MyDrive/YOLOv7_tiny/yolov7/data/coco.yaml"
  - "--weights=/content/gdrive/MyDrive/YOLOv7_tiny/yolov7/yolov7-tiny.pt"
  - "--cfg=/content/gdrive/MyDrive/YOLOv7_tiny/yolov7/cfg/training/yolov7-tiny.yaml"
```
2. Run the first CLI command in either the terminal or a Jupyter notebook by starting with %%bash.
```
%%bash
wandb sweep --project your_sweep_project_name config.yaml
```
3. From the output of the second step, you will receive suggestions for the second CLI command, and you can specify the number of iterations you want. For example, the command for conducting hyperparameter tuning with 3 iterations could be:
```
%%bash
wandb agent --count 3 your-entity/sweep-demo-cli/sweepID
```
I hope this helps! Let me know if you have any questions.

**Comment by thanos-wandb** [comment]
Great, glad to hear this is now fixed, and thank you for the code snippet, @Achyar-CN - much appreciated!

**Comment by elon1992** [comment]
Hello @Achyar-CN , Thank you so much for the code snippet. But i have questions like the hyperparameter you chose for tuning is just epch what if i have to use batch-size which is used in args, and what if i want to try different optimizers or lr0 or anything. Will inserting the hyperparameter name and value works same as epoch?
Thank you

**Comment by Achyar-CN** [comment]
Hi @elon1992, from my understanding, there are two types of hyperparameters in YOLOv7: direct parser hyperparameters (such as epoch, batch-size, img, etc.) and hyperparameters included within hyperparameter.xml (like lr0, momentum, etc.). For instance, you could directly add both as shown below:
```
program: train.py
method: bayes
metric:
  goal: maximize
  name: metrics/mAP_0.5
parameters:
  epochs:
    values: [2, 3]
  batch-size:
    values: [8, 16, 32]
hyp:
  parameters:
    momentum: 
      values: [0.8]
    lr0:
        max: 0.02
        min: 0.005
        distribution: uniform
command:
  - ${env}
  - python
  - ${program}
  - ${args}
  - "--img=800"
  - "--device=0"
  - "--workers=4"
  - "--data=/content/gdrive/MyDrive/YOLOv7_tiny/yolov7/data/pothole.yaml"
  - "--weights=/content/gdrive/MyDrive/YOLOv7_tiny/yolov7/yolov7-tiny.pt"
  - "--cfg=/content/gdrive/MyDrive/YOLOv7_tiny/yolov7/cfg/training/yolov7_pothole-tiny.yaml"
```
