### ISSUE TITLE
[CLI]: wandb sweep command not prefixing runs with "python [filename].py"

### ISSUE THREAD

**Issue by Zafirmk** [wandb/wandb#7260]
### Describe the bug

I have the following `sweep.yaml` file
```
program: main_fl.py
command:
  - ${args_no_boolean_flags}
method: random
metric:
  goal: maximize
  name: rank_0/test_acc
parameters:
  optimizer_name:
    value: "SGD"
[MORE PARAMETERS HERE]
```
I have `${args_no_boolean_flags}` because I have certain parameters that are boolean flags. Solution obtained from [here](https://github.com/wandb/wandb/issues/1700). When executing the above yaml with the `wandb agent` command I get the following error:

``
FileNotFoundError: [Errno 2] No such file or directory: '--optimizer_name=SGD'
``
It attempts to run my python script without prepending `/usr/bin/env python main_fl.py`

I am able to run the sweep when I don't include `- ${args_no_boolean_flags}` - But I need this because of the boolean flag variables.

Expected behaviour is to have the sweep execute with the addition of `${args_no_boolean_flags}`

### Environment

WandB version: 0.16.2

OS: MacOS 14.3.1

Python version: 3.9.6
