### ISSUE TITLE
[Q] How to sweep parameters that is defined in config.yaml file

### ISSUE THREAD

**Issue by Yoonho-Na** [wandb/wandb#7737]
I have a config file for training like below.
```
# config.yaml
model_params:
  agent_params:
    lr_actor: 0.00003
    lr_critic: 0.0001
    gamma: 0.1
    gae_lambda: 0.95
    K_epochs: 10
    eps_clip: 0.2
    action_std_init: 0.6
    action_std_decay_rate: 0.02
    action_std_decay_freq: 10
    min_action_std: 0.1
    sub_step: 25
    batch_size: 16
    n_actions: 2
    input_dims: [256, 8, 16, 16]
    train_step: 5000

logger_params:
  wandb: True
  project: 'PPO'
  log_episode: 25
  seed: 7777
```

and I tried to use sweep for hyperparameter optimization by using below sweep configuration in wandb.ai.

```
program: main_ppo.py
method: bayes
metric:
  goal: maximize
  name: avg_score_within_past_100_ep
parameters:
  model_params:
    parameters:
      agent_params:
        parameters:
          lr_actor:
            max: 0.0003
            min: 0.00003
            distribution: uniform
          lr_critic:
            max: 0.0001
            min: 0.00001
            distribuiton: uniform
          gamma:
            max: 0.5
            min: 0
            distribution: uniform
          gae_lambda:
            max: 0.95
            min: 0.5
            distribution: uniform
          K_epochs:
            values: [5, 10, 20]
          eps_clip:
            values: [0.1, 0.2]
          action_std_decay_rate:
            values: [0.01, 0.02, 0.04, 0.08, 0.1]
          action_std_decay_freq:
            values: [10, 15, 20, 40]
          batch_size:
            values: [4, 8, 16, 32, 64]
```

I get an error
`Invalid sweep config: invalid hyperparameter configuration: model_params`
does anyone know why this is not working?

**Comment by gsaltintas** [comment]
@Yoonho-Na  I believe it is due to the typo in lr_critic's distrib**utio**n.

**Comment by Yoonho-Na** [comment]
@gsaltintas You're right. It was just an simple typo error... Thank you for the correction

**Comment by vitoria-wandb** [comment]
good catch, @gsaltintas !

@Yoonho-Na - are there any other issues you're encountering? Let us know!

**Comment by Yoonho-Na** [comment]
@vitoria-wandb @gsaltintas  
hello.
I'm still having issues with using sweep.
I believe this one doesn't have typo issue.

```
program: main_ppo_lstm.py
method: bayes
metric:
  goal: maximize
  name: valid_avg_return
parameters:
  n_envs:
    values: [4, 8, 16]
  n_steps:
    values: [15, 20, 25, 30]
  lr:
    max: 0.001
    min: 0.00001
    distribution: uniform
  gamma:
    values: [0, 0.1, 0.25, 0.5, 0.75, 1]
  gae_lambda:
    values: [0, 0.1, 0.25, 0.5, 0.75, 1]
  K_epochs:
    values: [2, 4, 8]
  clip_coef:
    values: [0.1, 0.2, 0.4]
  vf_coef:
    values: [0.25, 0.5, 0.75, 1]
  action_std_init:
    values: [0.4, 0.6, 0.8]
```

I created sweep agent with above settings but I got error

`
...
main_ppo_lstm.py: error: unrecognized arguments: --K_epochs=2 --action_std_init=0.6 --clip_coef=0.2 --gae_lambda=1 --gamma=1 --lr=0.00013351545699584631 --n_envs=16 --n_steps=15 --vf_coef=0.5
...
`

I think this error happened because my code doesn't have those keyword arguments itself.
currently, most of my configuration is done in the additional config.yaml file and I just load it.

```
agent:
  seed: 7777
  n_envs: 8
  total_steps: 1000000
  n_steps: 25
  lr: 0.0003
  anneal_lr: True
  ...
  latent_dim: [256, 8, 16, 16]

```

how can I use sweep with this settings??
