### ISSUE TITLE
[Bug]: Hierarchy config not displayed correctly

### ISSUE THREAD

**Issue by lhy0807** [wandb/wandb#8725]
### Describe the bug

The version of the wandb package you are using: 0.18.5
The version of Python you are using: 3.8
The version of the operating system you are using: ubuntu 20.04

When I pass the following config into `wandb.init`
```
dataloader:
  num_workers: 4
  batch_size: 32

trainer:
  epochs: 100
  lr: 0.001

network:
  choice: "dual" # "single" or "dual"
```

it would displayed incorrectly as ![Image](https://github.com/user-attachments/assets/c31c26c4-e061-4ef9-bea5-f45a579021ca). I remember in previous version, this issue didn't exist and the hyperparameters would be flattened
